# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\category_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryForm(object):
    def setupUi(self, CategoryForm):
        CategoryForm.setObjectName("CategoryForm")
        CategoryForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        CategoryForm.resize(400, 500)
        CategoryForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(CategoryForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.typeGroupBox = QtWidgets.QGroupBox(CategoryForm)
        self.typeGroupBox.setObjectName("typeGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.typeGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.incomeRadioButton = QtWidgets.QRadioButton(self.typeGroupBox)
        self.incomeRadioButton.setObjectName("incomeRadioButton")
        self.horizontalLayout_2.addWidget(self.incomeRadioButton)
        self.expenseRadioButton = QtWidgets.QRadioButton(self.typeGroupBox)
        self.expenseRadioButton.setObjectName("expenseRadioButton")
        self.horizontalLayout_2.addWidget(self.expenseRadioButton)
        self.incomeAndExpenseRadioButton = QtWidgets.QRadioButton(self.typeGroupBox)
        self.incomeAndExpenseRadioButton.setObjectName("incomeAndExpenseRadioButton")
        self.horizontalLayout_2.addWidget(self.incomeAndExpenseRadioButton)
        self.verticalLayout.addWidget(self.typeGroupBox)
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.expandAllToolButton = QtWidgets.QToolButton(CategoryForm)
        self.expandAllToolButton.setObjectName("expandAllToolButton")
        self.controlsHorizontalLayout.addWidget(self.expandAllToolButton)
        self.collapseAllToolButton = QtWidgets.QToolButton(CategoryForm)
        self.collapseAllToolButton.setObjectName("collapseAllToolButton")
        self.controlsHorizontalLayout.addWidget(self.collapseAllToolButton)
        self.addToolButton = QtWidgets.QToolButton(CategoryForm)
        self.addToolButton.setObjectName("addToolButton")
        self.controlsHorizontalLayout.addWidget(self.addToolButton)
        self.searchLineEdit = QtWidgets.QLineEdit(CategoryForm)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.controlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.verticalLayout.addLayout(self.controlsHorizontalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(CategoryForm)
        QtCore.QMetaObject.connectSlotsByName(CategoryForm)

    def retranslateUi(self, CategoryForm):
        _translate = QtCore.QCoreApplication.translate
        CategoryForm.setWindowTitle(_translate("CategoryForm", "Categories"))
        self.typeGroupBox.setTitle(_translate("CategoryForm", "Type"))
        self.incomeRadioButton.setText(_translate("CategoryForm", "Income"))
        self.expenseRadioButton.setText(_translate("CategoryForm", "Expense"))
        self.incomeAndExpenseRadioButton.setText(_translate("CategoryForm", "Income and Expense"))
        self.expandAllToolButton.setText(_translate("CategoryForm", "..."))
        self.collapseAllToolButton.setText(_translate("CategoryForm", "..."))
        self.addToolButton.setText(_translate("CategoryForm", "..."))
        self.searchLineEdit.setToolTip(_translate("CategoryForm", "<html><head/><body><p>Special characters:<br/>* matches zero or more of any characters<br/>? matches any single character<br/>[...] matches any character within square brackets</p></body></html>"))
        self.searchLineEdit.setPlaceholderText(_translate("CategoryForm", "Search Categories"))
