# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\quotes_update_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QuotesUpdateForm(object):
    def setupUi(self, QuotesUpdateForm):
        QuotesUpdateForm.setObjectName("QuotesUpdateForm")
        QuotesUpdateForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        QuotesUpdateForm.resize(350, 250)
        QuotesUpdateForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(QuotesUpdateForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(QuotesUpdateForm)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadQuotesPushButton = QtWidgets.QPushButton(QuotesUpdateForm)
        self.downloadQuotesPushButton.setObjectName("downloadQuotesPushButton")
        self.horizontalLayout.addWidget(self.downloadQuotesPushButton)
        self.saveQuotesPushButton = QtWidgets.QPushButton(QuotesUpdateForm)
        self.saveQuotesPushButton.setObjectName("saveQuotesPushButton")
        self.horizontalLayout.addWidget(self.saveQuotesPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(QuotesUpdateForm)
        QtCore.QMetaObject.connectSlotsByName(QuotesUpdateForm)

    def retranslateUi(self, QuotesUpdateForm):
        _translate = QtCore.QCoreApplication.translate
        QuotesUpdateForm.setWindowTitle(_translate("QuotesUpdateForm", "Update Quotes"))
        self.downloadQuotesPushButton.setText(_translate("QuotesUpdateForm", "Download quotes"))
        self.saveQuotesPushButton.setText(_translate("QuotesUpdateForm", "Save quotes"))
