# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\quotes_update_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QuotesUpdateForm(object):
    def setupUi(self, QuotesUpdateForm):
        QuotesUpdateForm.setObjectName("QuotesUpdateForm")
        QuotesUpdateForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        QuotesUpdateForm.resize(357, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(QuotesUpdateForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(QuotesUpdateForm)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.verticalLayout.addWidget(self.searchLineEdit)
        self.tableView = QtWidgets.QTableView(QuotesUpdateForm)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectAllToolButton = QtWidgets.QToolButton(QuotesUpdateForm)
        self.selectAllToolButton.setObjectName("selectAllToolButton")
        self.horizontalLayout.addWidget(self.selectAllToolButton)
        self.unselectAllToolButton = QtWidgets.QToolButton(QuotesUpdateForm)
        self.unselectAllToolButton.setObjectName("unselectAllToolButton")
        self.horizontalLayout.addWidget(self.unselectAllToolButton)
        self.downloadQuotesPushButton = QtWidgets.QPushButton(QuotesUpdateForm)
        self.downloadQuotesPushButton.setObjectName("downloadQuotesPushButton")
        self.horizontalLayout.addWidget(self.downloadQuotesPushButton)
        self.saveQuotesPushButton = QtWidgets.QPushButton(QuotesUpdateForm)
        self.saveQuotesPushButton.setObjectName("saveQuotesPushButton")
        self.horizontalLayout.addWidget(self.saveQuotesPushButton)
        self.helpPushButton = QtWidgets.QPushButton(QuotesUpdateForm)
        self.helpPushButton.setObjectName("helpPushButton")
        self.horizontalLayout.addWidget(self.helpPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionSelect_All = QtGui.QAction(QuotesUpdateForm)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionUnselect_All = QtGui.QAction(QuotesUpdateForm)
        self.actionUnselect_All.setObjectName("actionUnselect_All")

        self.retranslateUi(QuotesUpdateForm)
        QtCore.QMetaObject.connectSlotsByName(QuotesUpdateForm)

    def retranslateUi(self, QuotesUpdateForm):
        _translate = QtCore.QCoreApplication.translate
        QuotesUpdateForm.setWindowTitle(_translate("QuotesUpdateForm", "Update Quotes"))
        self.searchLineEdit.setToolTip(_translate("QuotesUpdateForm", "<html><head/><body><p>Special characters:</p><p>* matches zero or more of any characters<br/>? matches any single character<br/>[...] matches any character within square brackets</p></body></html>"))
        self.searchLineEdit.setPlaceholderText(_translate("QuotesUpdateForm", "Search Quotes"))
        self.selectAllToolButton.setText(_translate("QuotesUpdateForm", "..."))
        self.unselectAllToolButton.setText(_translate("QuotesUpdateForm", "..."))
        self.downloadQuotesPushButton.setText(_translate("QuotesUpdateForm", "Download selected"))
        self.saveQuotesPushButton.setText(_translate("QuotesUpdateForm", "Save selected"))
        self.helpPushButton.setText(_translate("QuotesUpdateForm", "Help"))
        self.actionSelect_All.setText(_translate("QuotesUpdateForm", "Select All"))
        self.actionUnselect_All.setText(_translate("QuotesUpdateForm", "Unselect All"))
