# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\security_account_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecurityAccountForm(object):
    def setupUi(self, SecurityAccountForm):
        SecurityAccountForm.setObjectName("SecurityAccountForm")
        SecurityAccountForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        SecurityAccountForm.resize(700, 200)
        SecurityAccountForm.setWindowTitle("")
        SecurityAccountForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(SecurityAccountForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(SecurityAccountForm)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(SecurityAccountForm)
        QtCore.QMetaObject.connectSlotsByName(SecurityAccountForm)

    def retranslateUi(self, SecurityAccountForm):
        pass
