# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\security_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecurityForm(object):
    def setupUi(self, SecurityForm):
        SecurityForm.setObjectName("SecurityForm")
        SecurityForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        SecurityForm.resize(725, 360)
        SecurityForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SecurityForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SecurityForm)
        self.tabWidget.setObjectName("tabWidget")
        self.manageSecuritiesTab = QtWidgets.QWidget()
        self.manageSecuritiesTab.setObjectName("manageSecuritiesTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.manageSecuritiesTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftVerticalLayout = QtWidgets.QVBoxLayout()
        self.leftVerticalLayout.setObjectName("leftVerticalLayout")
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(self.manageSecuritiesTab)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.controlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.leftVerticalLayout.addLayout(self.controlsHorizontalLayout)
        self.tableView = QtWidgets.QTableView(self.manageSecuritiesTab)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.leftVerticalLayout.addWidget(self.tableView)
        self.horizontalLayout_2.addLayout(self.leftVerticalLayout)
        self.rightVerticalLayout = QtWidgets.QVBoxLayout()
        self.rightVerticalLayout.setObjectName("rightVerticalLayout")
        self.addButton = QtWidgets.QPushButton(self.manageSecuritiesTab)
        self.addButton.setObjectName("addButton")
        self.rightVerticalLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.manageSecuritiesTab)
        self.editButton.setObjectName("editButton")
        self.rightVerticalLayout.addWidget(self.editButton)
        self.setPriceButton = QtWidgets.QPushButton(self.manageSecuritiesTab)
        self.setPriceButton.setObjectName("setPriceButton")
        self.rightVerticalLayout.addWidget(self.setPriceButton)
        self.removeButton = QtWidgets.QPushButton(self.manageSecuritiesTab)
        self.removeButton.setObjectName("removeButton")
        self.rightVerticalLayout.addWidget(self.removeButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightVerticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.rightVerticalLayout)
        self.tabWidget.addTab(self.manageSecuritiesTab, "")
        self.securitiesOverviewTab = QtWidgets.QWidget()
        self.securitiesOverviewTab.setObjectName("securitiesOverviewTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.securitiesOverviewTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.treeView = QtWidgets.QTreeView(self.securitiesOverviewTab)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setSortingEnabled(True)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_3.addWidget(self.treeView)
        self.tabWidget.addTab(self.securitiesOverviewTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(SecurityForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SecurityForm)

    def retranslateUi(self, SecurityForm):
        _translate = QtCore.QCoreApplication.translate
        SecurityForm.setWindowTitle(_translate("SecurityForm", "Securities"))
        self.searchLineEdit.setToolTip(_translate("SecurityForm", "<html><head/><body><p>Special characters:</p><p>* matches zero or more of any characters<br/>? matches any single character<br/>[...] matches any character within square brackets</p></body></html>"))
        self.searchLineEdit.setPlaceholderText(_translate("SecurityForm", "Search Securities"))
        self.addButton.setText(_translate("SecurityForm", "Add"))
        self.editButton.setText(_translate("SecurityForm", "Edit"))
        self.setPriceButton.setText(_translate("SecurityForm", "Set price"))
        self.removeButton.setText(_translate("SecurityForm", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manageSecuritiesTab), _translate("SecurityForm", "Manage Securities"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.securitiesOverviewTab), _translate("SecurityForm", "Securities Overview"))
