# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\tag_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TagForm(object):
    def setupUi(self, TagForm):
        TagForm.setObjectName("TagForm")
        TagForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TagForm.resize(350, 350)
        TagForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(TagForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftVerticalLayout = QtWidgets.QVBoxLayout()
        self.leftVerticalLayout.setObjectName("leftVerticalLayout")
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.addToolButton = QtWidgets.QToolButton(TagForm)
        self.addToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.addToolButton.setObjectName("addToolButton")
        self.controlsHorizontalLayout.addWidget(self.addToolButton)
        self.renameToolButton = QtWidgets.QToolButton(TagForm)
        self.renameToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.renameToolButton.setObjectName("renameToolButton")
        self.controlsHorizontalLayout.addWidget(self.renameToolButton)
        self.removeToolButton = QtWidgets.QToolButton(TagForm)
        self.removeToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.removeToolButton.setObjectName("removeToolButton")
        self.controlsHorizontalLayout.addWidget(self.removeToolButton)
        self.searchLineEdit = QtWidgets.QLineEdit(TagForm)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.controlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.leftVerticalLayout.addLayout(self.controlsHorizontalLayout)
        self.tableView = QtWidgets.QTableView(TagForm)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.leftVerticalLayout.addWidget(self.tableView)
        self.horizontalLayout.addLayout(self.leftVerticalLayout)
        self.actionAdd_Tag = QtGui.QAction(TagForm)
        self.actionAdd_Tag.setObjectName("actionAdd_Tag")
        self.actionRename_Tag = QtGui.QAction(TagForm)
        self.actionRename_Tag.setObjectName("actionRename_Tag")
        self.actionRemove_Tag = QtGui.QAction(TagForm)
        self.actionRemove_Tag.setObjectName("actionRemove_Tag")

        self.retranslateUi(TagForm)
        QtCore.QMetaObject.connectSlotsByName(TagForm)

    def retranslateUi(self, TagForm):
        _translate = QtCore.QCoreApplication.translate
        TagForm.setWindowTitle(_translate("TagForm", "Tags"))
        self.addToolButton.setText(_translate("TagForm", "..."))
        self.renameToolButton.setText(_translate("TagForm", "..."))
        self.removeToolButton.setText(_translate("TagForm", "..."))
        self.searchLineEdit.setToolTip(_translate("TagForm", "<html><head/><body><p>Special characters:</p><p>* matches zero or more of any characters<br/>? matches any single character<br/>[...] matches any character within square brackets</p></body></html>"))
        self.searchLineEdit.setPlaceholderText(_translate("TagForm", "Search Tags"))
        self.actionAdd_Tag.setText(_translate("TagForm", "Add Tag"))
        self.actionAdd_Tag.setToolTip(_translate("TagForm", "Add Tag"))
        self.actionRename_Tag.setText(_translate("TagForm", "Rename Tag"))
        self.actionRemove_Tag.setText(_translate("TagForm", "Remove Tag"))
        self.actionRemove_Tag.setToolTip(_translate("TagForm", "Remove Tag"))
