# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\table_view_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TableViewForm(object):
    def setupUi(self, TableViewForm):
        TableViewForm.setObjectName("TableViewForm")
        TableViewForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TableViewForm.resize(800, 500)
        TableViewForm.setWindowTitle("")
        TableViewForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(TableViewForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(TableViewForm)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.verticalLayout.addWidget(self.searchLineEdit)
        self.tableView = QtWidgets.QTableView(TableViewForm)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shownTransactionsLabel = QtWidgets.QLabel(TableViewForm)
        self.shownTransactionsLabel.setObjectName("shownTransactionsLabel")
        self.horizontalLayout.addWidget(self.shownTransactionsLabel)
        self.line = QtWidgets.QFrame(TableViewForm)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.selectedTransactionsTotalLabel = QtWidgets.QLabel(TableViewForm)
        self.selectedTransactionsTotalLabel.setObjectName("selectedTransactionsTotalLabel")
        self.horizontalLayout.addWidget(self.selectedTransactionsTotalLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TableViewForm)
        QtCore.QMetaObject.connectSlotsByName(TableViewForm)

    def retranslateUi(self, TableViewForm):
        _translate = QtCore.QCoreApplication.translate
        self.shownTransactionsLabel.setToolTip(_translate("TableViewForm", "<html><head/><body><p>Shows how many Transactions have passed the Transaction Filter and are listed in Transaction Table.</p></body></html>"))
        self.shownTransactionsLabel.setText(_translate("TableViewForm", "Showing Transactions: 0 / 0"))
        self.selectedTransactionsTotalLabel.setToolTip(_translate("TableViewForm", "<html><head/><body><p>Only Income, Expense and Refund Transaction amounts are used in the calculation.</p></body></html>"))
        self.selectedTransactionsTotalLabel.setText(_translate("TableViewForm", "Selected Transactions Total: ??? XXX "))
