# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\forms\tag_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TagForm(object):
    def setupUi(self, TagForm):
        TagForm.setObjectName("TagForm")
        TagForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TagForm.resize(425, 360)
        TagForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(TagForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftVerticalLayout = QtWidgets.QVBoxLayout()
        self.leftVerticalLayout.setObjectName("leftVerticalLayout")
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(TagForm)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.controlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.leftVerticalLayout.addLayout(self.controlsHorizontalLayout)
        self.tableView = QtWidgets.QTableView(TagForm)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.leftVerticalLayout.addWidget(self.tableView)
        self.horizontalLayout.addLayout(self.leftVerticalLayout)
        self.rightVerticalLayout = QtWidgets.QVBoxLayout()
        self.rightVerticalLayout.setObjectName("rightVerticalLayout")
        self.addButton = QtWidgets.QPushButton(TagForm)
        self.addButton.setObjectName("addButton")
        self.rightVerticalLayout.addWidget(self.addButton)
        self.renameButton = QtWidgets.QPushButton(TagForm)
        self.renameButton.setObjectName("renameButton")
        self.rightVerticalLayout.addWidget(self.renameButton)
        self.removeButton = QtWidgets.QPushButton(TagForm)
        self.removeButton.setObjectName("removeButton")
        self.rightVerticalLayout.addWidget(self.removeButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightVerticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.rightVerticalLayout)

        self.retranslateUi(TagForm)
        QtCore.QMetaObject.connectSlotsByName(TagForm)

    def retranslateUi(self, TagForm):
        _translate = QtCore.QCoreApplication.translate
        TagForm.setWindowTitle(_translate("TagForm", "Tags"))
        self.searchLineEdit.setToolTip(_translate("TagForm", "<html><head/><body><p>Special characters:</p><p>* matches zero or more of any characters<br/>? matches any single character<br/>[...] matches any character within square brackets</p></body></html>"))
        self.searchLineEdit.setPlaceholderText(_translate("TagForm", "Search Tags"))
        self.addButton.setText(_translate("TagForm", "Add"))
        self.renameButton.setText(_translate("TagForm", "Rename"))
        self.removeButton.setText(_translate("TagForm", "Remove"))
