# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\category_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryForm(object):
    def setupUi(self, CategoryForm):
        CategoryForm.setObjectName("CategoryForm")
        CategoryForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        CategoryForm.resize(425, 454)
        CategoryForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(CategoryForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftVerticalLayout = QtWidgets.QVBoxLayout()
        self.leftVerticalLayout.setObjectName("leftVerticalLayout")
        self.typeGroupBox = QtWidgets.QGroupBox(CategoryForm)
        self.typeGroupBox.setObjectName("typeGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.typeGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.incomeRadioButton = QtWidgets.QRadioButton(self.typeGroupBox)
        self.incomeRadioButton.setObjectName("incomeRadioButton")
        self.horizontalLayout_2.addWidget(self.incomeRadioButton)
        self.expenseRadioButton = QtWidgets.QRadioButton(self.typeGroupBox)
        self.expenseRadioButton.setObjectName("expenseRadioButton")
        self.horizontalLayout_2.addWidget(self.expenseRadioButton)
        self.incomeAndExpenseRadioButton = QtWidgets.QRadioButton(self.typeGroupBox)
        self.incomeAndExpenseRadioButton.setObjectName("incomeAndExpenseRadioButton")
        self.horizontalLayout_2.addWidget(self.incomeAndExpenseRadioButton)
        self.leftVerticalLayout.addWidget(self.typeGroupBox)
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.addToolButton = QtWidgets.QToolButton(CategoryForm)
        self.addToolButton.setObjectName("addToolButton")
        self.controlsHorizontalLayout.addWidget(self.addToolButton)
        self.editToolButton = QtWidgets.QToolButton(CategoryForm)
        self.editToolButton.setObjectName("editToolButton")
        self.controlsHorizontalLayout.addWidget(self.editToolButton)
        self.removeToolButton = QtWidgets.QToolButton(CategoryForm)
        self.removeToolButton.setObjectName("removeToolButton")
        self.controlsHorizontalLayout.addWidget(self.removeToolButton)
        self.searchLineEdit = QtWidgets.QLineEdit(CategoryForm)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.controlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.leftVerticalLayout.addLayout(self.controlsHorizontalLayout)
        self.treeView = QtWidgets.QTreeView(CategoryForm)
        self.treeView.setObjectName("treeView")
        self.leftVerticalLayout.addWidget(self.treeView)
        self.horizontalLayout.addLayout(self.leftVerticalLayout)

        self.retranslateUi(CategoryForm)
        QtCore.QMetaObject.connectSlotsByName(CategoryForm)

    def retranslateUi(self, CategoryForm):
        _translate = QtCore.QCoreApplication.translate
        CategoryForm.setWindowTitle(_translate("CategoryForm", "Categories"))
        self.typeGroupBox.setTitle(_translate("CategoryForm", "Type"))
        self.incomeRadioButton.setText(_translate("CategoryForm", "Income"))
        self.expenseRadioButton.setText(_translate("CategoryForm", "Expense"))
        self.incomeAndExpenseRadioButton.setText(_translate("CategoryForm", "Income and Expense"))
        self.addToolButton.setText(_translate("CategoryForm", "..."))
        self.editToolButton.setText(_translate("CategoryForm", "..."))
        self.removeToolButton.setText(_translate("CategoryForm", "..."))
        self.searchLineEdit.setPlaceholderText(_translate("CategoryForm", "Search..."))
