# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\currency_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CurrencyForm(object):
    def setupUi(self, CurrencyForm):
        CurrencyForm.setObjectName("CurrencyForm")
        CurrencyForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        CurrencyForm.resize(325, 325)
        CurrencyForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(CurrencyForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(CurrencyForm)
        self.tabWidget.setObjectName("tabWidget")
        self.currencyTab = QtWidgets.QWidget()
        self.currencyTab.setObjectName("currencyTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.currencyTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.currencyTable = QtWidgets.QTableView(self.currencyTab)
        self.currencyTable.setObjectName("currencyTable")
        self.horizontalLayout_2.addWidget(self.currencyTable)
        self.currencyButtonLayout = QtWidgets.QVBoxLayout()
        self.currencyButtonLayout.setObjectName("currencyButtonLayout")
        self.addCurrencyButton = QtWidgets.QPushButton(self.currencyTab)
        self.addCurrencyButton.setObjectName("addCurrencyButton")
        self.currencyButtonLayout.addWidget(self.addCurrencyButton)
        self.removeCurrencyButton = QtWidgets.QPushButton(self.currencyTab)
        self.removeCurrencyButton.setObjectName("removeCurrencyButton")
        self.currencyButtonLayout.addWidget(self.removeCurrencyButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.currencyButtonLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.currencyButtonLayout)
        self.tabWidget.addTab(self.currencyTab, "")
        self.exchangeRateTab = QtWidgets.QWidget()
        self.exchangeRateTab.setObjectName("exchangeRateTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.exchangeRateTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exchangeRateTable = QtWidgets.QTableView(self.exchangeRateTab)
        self.exchangeRateTable.setObjectName("exchangeRateTable")
        self.horizontalLayout_3.addWidget(self.exchangeRateTable)
        self.exchangeRateButtonLayout = QtWidgets.QVBoxLayout()
        self.exchangeRateButtonLayout.setObjectName("exchangeRateButtonLayout")
        self.addExchangeRateButton = QtWidgets.QPushButton(self.exchangeRateTab)
        self.addExchangeRateButton.setObjectName("addExchangeRateButton")
        self.exchangeRateButtonLayout.addWidget(self.addExchangeRateButton)
        self.removeExchangeRateButton = QtWidgets.QPushButton(self.exchangeRateTab)
        self.removeExchangeRateButton.setObjectName("removeExchangeRateButton")
        self.exchangeRateButtonLayout.addWidget(self.removeExchangeRateButton)
        self.setExchangeRateButton = QtWidgets.QPushButton(self.exchangeRateTab)
        self.setExchangeRateButton.setObjectName("setExchangeRateButton")
        self.exchangeRateButtonLayout.addWidget(self.setExchangeRateButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.exchangeRateButtonLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.exchangeRateButtonLayout)
        self.tabWidget.addTab(self.exchangeRateTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(CurrencyForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CurrencyForm)

    def retranslateUi(self, CurrencyForm):
        _translate = QtCore.QCoreApplication.translate
        CurrencyForm.setWindowTitle(_translate("CurrencyForm", "Currencies and Exchange Rates"))
        self.addCurrencyButton.setText(_translate("CurrencyForm", "Add"))
        self.removeCurrencyButton.setText(_translate("CurrencyForm", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.currencyTab), _translate("CurrencyForm", "Currencies"))
        self.addExchangeRateButton.setText(_translate("CurrencyForm", "Add"))
        self.removeExchangeRateButton.setText(_translate("CurrencyForm", "Remove"))
        self.setExchangeRateButton.setText(_translate("CurrencyForm", "Set Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exchangeRateTab), _translate("CurrencyForm", "Exchange Rates"))
