# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\payee_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PayeeForm(object):
    def setupUi(self, PayeeForm):
        PayeeForm.setObjectName("PayeeForm")
        PayeeForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        PayeeForm.resize(371, 360)
        PayeeForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(PayeeForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftVerticalLayout = QtWidgets.QVBoxLayout()
        self.leftVerticalLayout.setObjectName("leftVerticalLayout")
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.sortAscendingButton = QtWidgets.QToolButton(PayeeForm)
        self.sortAscendingButton.setObjectName("sortAscendingButton")
        self.controlsHorizontalLayout.addWidget(self.sortAscendingButton)
        self.sortDescendingButton = QtWidgets.QToolButton(PayeeForm)
        self.sortDescendingButton.setObjectName("sortDescendingButton")
        self.controlsHorizontalLayout.addWidget(self.sortDescendingButton)
        self.searchLineEdit = QtWidgets.QLineEdit(PayeeForm)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.controlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.leftVerticalLayout.addLayout(self.controlsHorizontalLayout)
        self.listView = QtWidgets.QListView(PayeeForm)
        self.listView.setObjectName("listView")
        self.leftVerticalLayout.addWidget(self.listView)
        self.horizontalLayout.addLayout(self.leftVerticalLayout)
        self.rightVerticalLayout = QtWidgets.QVBoxLayout()
        self.rightVerticalLayout.setObjectName("rightVerticalLayout")
        self.addButton = QtWidgets.QPushButton(PayeeForm)
        self.addButton.setObjectName("addButton")
        self.rightVerticalLayout.addWidget(self.addButton)
        self.renameButton = QtWidgets.QPushButton(PayeeForm)
        self.renameButton.setObjectName("renameButton")
        self.rightVerticalLayout.addWidget(self.renameButton)
        self.removeButton = QtWidgets.QPushButton(PayeeForm)
        self.removeButton.setObjectName("removeButton")
        self.rightVerticalLayout.addWidget(self.removeButton)
        self.selectButton = QtWidgets.QPushButton(PayeeForm)
        self.selectButton.setObjectName("selectButton")
        self.rightVerticalLayout.addWidget(self.selectButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightVerticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.rightVerticalLayout)

        self.retranslateUi(PayeeForm)
        QtCore.QMetaObject.connectSlotsByName(PayeeForm)

    def retranslateUi(self, PayeeForm):
        _translate = QtCore.QCoreApplication.translate
        PayeeForm.setWindowTitle(_translate("PayeeForm", "Payees"))
        self.sortAscendingButton.setText(_translate("PayeeForm", "..."))
        self.sortDescendingButton.setText(_translate("PayeeForm", "..."))
        self.searchLineEdit.setPlaceholderText(_translate("PayeeForm", "Search..."))
        self.addButton.setText(_translate("PayeeForm", "Add"))
        self.renameButton.setText(_translate("PayeeForm", "Rename"))
        self.removeButton.setText(_translate("PayeeForm", "Remove"))
        self.selectButton.setText(_translate("PayeeForm", "Select"))
