# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\security_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecurityForm(object):
    def setupUi(self, SecurityForm):
        SecurityForm.setObjectName("SecurityForm")
        SecurityForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        SecurityForm.resize(725, 360)
        SecurityForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SecurityForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftVerticalLayout = QtWidgets.QVBoxLayout()
        self.leftVerticalLayout.setObjectName("leftVerticalLayout")
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(SecurityForm)
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.controlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.leftVerticalLayout.addLayout(self.controlsHorizontalLayout)
        self.tableView = QtWidgets.QTableView(SecurityForm)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setHighlightSections(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.leftVerticalLayout.addWidget(self.tableView)
        self.horizontalLayout.addLayout(self.leftVerticalLayout)
        self.rightVerticalLayout = QtWidgets.QVBoxLayout()
        self.rightVerticalLayout.setObjectName("rightVerticalLayout")
        self.addButton = QtWidgets.QPushButton(SecurityForm)
        self.addButton.setObjectName("addButton")
        self.rightVerticalLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(SecurityForm)
        self.editButton.setObjectName("editButton")
        self.rightVerticalLayout.addWidget(self.editButton)
        self.setPriceButton = QtWidgets.QPushButton(SecurityForm)
        self.setPriceButton.setObjectName("setPriceButton")
        self.rightVerticalLayout.addWidget(self.setPriceButton)
        self.removeButton = QtWidgets.QPushButton(SecurityForm)
        self.removeButton.setObjectName("removeButton")
        self.rightVerticalLayout.addWidget(self.removeButton)
        self.selectButton = QtWidgets.QPushButton(SecurityForm)
        self.selectButton.setObjectName("selectButton")
        self.rightVerticalLayout.addWidget(self.selectButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightVerticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.rightVerticalLayout)

        self.retranslateUi(SecurityForm)
        QtCore.QMetaObject.connectSlotsByName(SecurityForm)

    def retranslateUi(self, SecurityForm):
        _translate = QtCore.QCoreApplication.translate
        SecurityForm.setWindowTitle(_translate("SecurityForm", "Securities"))
        self.searchLineEdit.setPlaceholderText(_translate("SecurityForm", "Search..."))
        self.addButton.setText(_translate("SecurityForm", "Add"))
        self.editButton.setText(_translate("SecurityForm", "Edit"))
        self.setPriceButton.setText(_translate("SecurityForm", "Set price"))
        self.removeButton.setText(_translate("SecurityForm", "Remove"))
        self.selectButton.setText(_translate("SecurityForm", "Select"))
