# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\busy_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BusyDialog(object):
    def setupUi(self, BusyDialog):
        BusyDialog.setObjectName("BusyDialog")
        BusyDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        BusyDialog.resize(340, 86)
        self.verticalLayout = QtWidgets.QVBoxLayout(BusyDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconLabel = QtWidgets.QLabel(BusyDialog)
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout.addWidget(self.iconLabel)
        self.label = QtWidgets.QLabel(BusyDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(BusyDialog)
        self.progressBar.setMaximum(3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.belowLabel = QtWidgets.QLabel(BusyDialog)
        self.belowLabel.setObjectName("belowLabel")
        self.verticalLayout.addWidget(self.belowLabel)

        self.retranslateUi(BusyDialog)
        QtCore.QMetaObject.connectSlotsByName(BusyDialog)

    def retranslateUi(self, BusyDialog):
        _translate = QtCore.QCoreApplication.translate
        BusyDialog.setWindowTitle(_translate("BusyDialog", "Dialog"))
        self.label.setText(_translate("BusyDialog", "TextLabel"))
        self.progressBar.setFormat(_translate("BusyDialog", "%v/%m"))
        self.belowLabel.setText(_translate("BusyDialog", "Loading can take more than a minute for huge files (>10 MB)"))
