# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\cash_transaction_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CashTransactionDialog(object):
    def setupUi(self, CashTransactionDialog):
        CashTransactionDialog.setObjectName("CashTransactionDialog")
        CashTransactionDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        CashTransactionDialog.resize(218, 142)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CashTransactionDialog.sizePolicy().hasHeightForWidth())
        CashTransactionDialog.setSizePolicy(sizePolicy)
        CashTransactionDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(CashTransactionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.typeLabel = QtWidgets.QLabel(CashTransactionDialog)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.typeLabel)
        self.radioButtonHorizontalLayout = QtWidgets.QHBoxLayout()
        self.radioButtonHorizontalLayout.setObjectName("radioButtonHorizontalLayout")
        self.incomeRadioButton = QtWidgets.QRadioButton(CashTransactionDialog)
        self.incomeRadioButton.setObjectName("incomeRadioButton")
        self.radioButtonHorizontalLayout.addWidget(self.incomeRadioButton)
        self.expenseRadioButton = QtWidgets.QRadioButton(CashTransactionDialog)
        self.expenseRadioButton.setObjectName("expenseRadioButton")
        self.radioButtonHorizontalLayout.addWidget(self.expenseRadioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.radioButtonHorizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioButtonHorizontalLayout)
        self.dateLabel = QtWidgets.QLabel(CashTransactionDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.dateEdit = QtWidgets.QDateEdit(CashTransactionDialog)
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit)
        self.amountLabel = QtWidgets.QLabel(CashTransactionDialog)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel)
        self.amountDoubleSpinBox = QtWidgets.QDoubleSpinBox(CashTransactionDialog)
        self.amountDoubleSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amountDoubleSpinBox.setProperty("showGroupSeparator", True)
        self.amountDoubleSpinBox.setMaximum(1e+16)
        self.amountDoubleSpinBox.setObjectName("amountDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.amountDoubleSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(CashTransactionDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.NoButton)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.actionSelect_Payee = QtGui.QAction(CashTransactionDialog)
        self.actionSelect_Payee.setObjectName("actionSelect_Payee")
        self.actionSelect_Tag = QtGui.QAction(CashTransactionDialog)
        self.actionSelect_Tag.setObjectName("actionSelect_Tag")
        self.actionSelect_Account = QtGui.QAction(CashTransactionDialog)
        self.actionSelect_Account.setObjectName("actionSelect_Account")

        self.retranslateUi(CashTransactionDialog)
        QtCore.QMetaObject.connectSlotsByName(CashTransactionDialog)
        CashTransactionDialog.setTabOrder(self.incomeRadioButton, self.expenseRadioButton)
        CashTransactionDialog.setTabOrder(self.expenseRadioButton, self.dateEdit)
        CashTransactionDialog.setTabOrder(self.dateEdit, self.amountDoubleSpinBox)

    def retranslateUi(self, CashTransactionDialog):
        _translate = QtCore.QCoreApplication.translate
        CashTransactionDialog.setWindowTitle(_translate("CashTransactionDialog", "Dialog"))
        self.typeLabel.setText(_translate("CashTransactionDialog", "Type"))
        self.incomeRadioButton.setText(_translate("CashTransactionDialog", "Income"))
        self.expenseRadioButton.setText(_translate("CashTransactionDialog", "Expense"))
        self.dateLabel.setText(_translate("CashTransactionDialog", "Date"))
        self.dateEdit.setDisplayFormat(_translate("CashTransactionDialog", "dd.MM.yyyy hh:mm"))
        self.amountLabel.setText(_translate("CashTransactionDialog", "Amount"))
        self.actionSelect_Payee.setText(_translate("CashTransactionDialog", "Select Payee"))
        self.actionSelect_Tag.setText(_translate("CashTransactionDialog", "Select Tag"))
        self.actionSelect_Account.setText(_translate("CashTransactionDialog", "Select Account"))
