# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\cash_transfer_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CashTransferDialog(object):
    def setupUi(self, CashTransferDialog):
        CashTransferDialog.setObjectName("CashTransferDialog")
        CashTransferDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        CashTransferDialog.resize(224, 141)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CashTransferDialog.sizePolicy().hasHeightForWidth())
        CashTransferDialog.setSizePolicy(sizePolicy)
        CashTransferDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.formLayout = QtWidgets.QFormLayout(CashTransferDialog)
        self.formLayout.setObjectName("formLayout")
        self.sentLabel = QtWidgets.QLabel(CashTransferDialog)
        self.sentLabel.setObjectName("sentLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sentLabel)
        self.sentDoubleSpinBox = QtWidgets.QDoubleSpinBox(CashTransferDialog)
        self.sentDoubleSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sentDoubleSpinBox.setProperty("showGroupSeparator", True)
        self.sentDoubleSpinBox.setMaximum(1e+16)
        self.sentDoubleSpinBox.setObjectName("sentDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sentDoubleSpinBox)
        self.receivedLabel = QtWidgets.QLabel(CashTransferDialog)
        self.receivedLabel.setObjectName("receivedLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.receivedLabel)
        self.receivedDoubleSpinBox = QtWidgets.QDoubleSpinBox(CashTransferDialog)
        self.receivedDoubleSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.receivedDoubleSpinBox.setProperty("showGroupSeparator", True)
        self.receivedDoubleSpinBox.setMaximum(1e+16)
        self.receivedDoubleSpinBox.setObjectName("receivedDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.receivedDoubleSpinBox)
        self.exchangeRateLabel = QtWidgets.QLabel(CashTransferDialog)
        self.exchangeRateLabel.setObjectName("exchangeRateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.exchangeRateLabel)
        self.exchangeRateLineEdit = QtWidgets.QLineEdit(CashTransferDialog)
        self.exchangeRateLineEdit.setEnabled(False)
        self.exchangeRateLineEdit.setStyleSheet("")
        self.exchangeRateLineEdit.setReadOnly(True)
        self.exchangeRateLineEdit.setObjectName("exchangeRateLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.exchangeRateLineEdit)
        self.dateLabel = QtWidgets.QLabel(CashTransferDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(CashTransferDialog)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateTimeEdit)
        self.actionSelect_Sender = QtGui.QAction(CashTransferDialog)
        self.actionSelect_Sender.setObjectName("actionSelect_Sender")
        self.actionSelect_Recipient = QtGui.QAction(CashTransferDialog)
        self.actionSelect_Recipient.setObjectName("actionSelect_Recipient")

        self.retranslateUi(CashTransferDialog)
        QtCore.QMetaObject.connectSlotsByName(CashTransferDialog)

    def retranslateUi(self, CashTransferDialog):
        _translate = QtCore.QCoreApplication.translate
        CashTransferDialog.setWindowTitle(_translate("CashTransferDialog", "Dialog"))
        self.sentLabel.setText(_translate("CashTransferDialog", "Sent"))
        self.receivedLabel.setText(_translate("CashTransferDialog", "Received"))
        self.exchangeRateLabel.setText(_translate("CashTransferDialog", "Exchange Rate"))
        self.dateLabel.setText(_translate("CashTransferDialog", "Date"))
        self.dateTimeEdit.setDisplayFormat(_translate("CashTransferDialog", "dd.MM.yyyy hh:mm"))
        self.actionSelect_Sender.setText(_translate("CashTransferDialog", "Select Sender"))
        self.actionSelect_Recipient.setText(_translate("CashTransferDialog", "Select Recipient"))
