# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\load_data_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadDataDialog(object):
    def setupUi(self, LoadDataDialog):
        LoadDataDialog.setObjectName("LoadDataDialog")
        LoadDataDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        LoadDataDialog.resize(350, 210)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoadDataDialog.sizePolicy().hasHeightForWidth())
        LoadDataDialog.setSizePolicy(sizePolicy)
        LoadDataDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadDataDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pathLabel = QtWidgets.QLabel(LoadDataDialog)
        self.pathLabel.setObjectName("pathLabel")
        self.horizontalLayout.addWidget(self.pathLabel)
        self.pathLineEdit = QtWidgets.QLineEdit(LoadDataDialog)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.horizontalLayout.addWidget(self.pathLineEdit)
        self.pathToolButton = QtWidgets.QToolButton(LoadDataDialog)
        self.pathToolButton.setObjectName("pathToolButton")
        self.horizontalLayout.addWidget(self.pathToolButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(LoadDataDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.keepRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.keepRadioButton.setChecked(True)
        self.keepRadioButton.setObjectName("keepRadioButton")
        self.verticalLayout_2.addWidget(self.keepRadioButton)
        self.overwriteRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.overwriteRadioButton.setObjectName("overwriteRadioButton")
        self.verticalLayout_2.addWidget(self.overwriteRadioButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(LoadDataDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(LoadDataDialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoadDataDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.actionSelect_File = QtGui.QAction(LoadDataDialog)
        self.actionSelect_File.setObjectName("actionSelect_File")

        self.retranslateUi(LoadDataDialog)
        QtCore.QMetaObject.connectSlotsByName(LoadDataDialog)

    def retranslateUi(self, LoadDataDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadDataDialog.setWindowTitle(_translate("LoadDataDialog", "Payee Dialog"))
        self.pathLabel.setText(_translate("LoadDataDialog", "Path"))
        self.pathLineEdit.setPlaceholderText(_translate("LoadDataDialog", "Enter CSV file path"))
        self.pathToolButton.setText(_translate("LoadDataDialog", "..."))
        self.groupBox.setTitle(_translate("LoadDataDialog", "Conflicting data"))
        self.keepRadioButton.setText(_translate("LoadDataDialog", "Keep current data"))
        self.overwriteRadioButton.setText(_translate("LoadDataDialog", "Overwrite current data with new data"))
        self.label.setText(_translate("LoadDataDialog", "<html><head/><body><p>Expected CSV data format is &quot;YYYY-MM-DD, #.###&quot;</p></body></html>"))
        self.actionSelect_File.setText(_translate("LoadDataDialog", "Select File"))
