# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\set_security_price_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SetSecurityPriceDialog(object):
    def setupUi(self, SetSecurityPriceDialog):
        SetSecurityPriceDialog.setObjectName("SetSecurityPriceDialog")
        SetSecurityPriceDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        SetSecurityPriceDialog.resize(229, 106)
        SetSecurityPriceDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(SetSecurityPriceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.priceLabel = QtWidgets.QLabel(SetSecurityPriceDialog)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priceLabel)
        self.dateLabel = QtWidgets.QLabel(SetSecurityPriceDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.priceDoubleSpinBox = QtWidgets.QDoubleSpinBox(SetSecurityPriceDialog)
        self.priceDoubleSpinBox.setDecimals(9)
        self.priceDoubleSpinBox.setObjectName("priceDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priceDoubleSpinBox)
        self.dateEdit = QtWidgets.QDateEdit(SetSecurityPriceDialog)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetSecurityPriceDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SetSecurityPriceDialog)
        QtCore.QMetaObject.connectSlotsByName(SetSecurityPriceDialog)

    def retranslateUi(self, SetSecurityPriceDialog):
        _translate = QtCore.QCoreApplication.translate
        SetSecurityPriceDialog.setWindowTitle(_translate("SetSecurityPriceDialog", "Set Security Price"))
        self.priceLabel.setText(_translate("SetSecurityPriceDialog", "Price"))
        self.dateLabel.setText(_translate("SetSecurityPriceDialog", "Date"))
