# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\select_item_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectItemDialog(object):
    def setupUi(self, SelectItemDialog):
        SelectItemDialog.setObjectName("SelectItemDialog")
        SelectItemDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        SelectItemDialog.resize(325, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SelectItemDialog.sizePolicy().hasHeightForWidth())
        SelectItemDialog.setSizePolicy(sizePolicy)
        SelectItemDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectItemDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(SelectItemDialog)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.verticalLayout.addWidget(self.searchLineEdit)
        self.listView = QtWidgets.QListView(SelectItemDialog)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectItemDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SelectItemDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectItemDialog)

    def retranslateUi(self, SelectItemDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectItemDialog.setWindowTitle(_translate("SelectItemDialog", "Select Item"))
        self.searchLineEdit.setToolTip(_translate("SelectItemDialog", "<html><head/><body><p>Special characters:</p><p>* matches zero or more of any characters<br/>? matches any single character<br/>[...] matches any character within square brackets</p></body></html>"))
        self.searchLineEdit.setPlaceholderText(_translate("SelectItemDialog", "Search..."))
