# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\transaction_tags_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TransactionTagsDialog(object):
    def setupUi(self, TransactionTagsDialog):
        TransactionTagsDialog.setObjectName("TransactionTagsDialog")
        TransactionTagsDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TransactionTagsDialog.resize(300, 74)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TransactionTagsDialog.sizePolicy().hasHeightForWidth())
        TransactionTagsDialog.setSizePolicy(sizePolicy)
        TransactionTagsDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.formLayout = QtWidgets.QFormLayout(TransactionTagsDialog)
        self.formLayout.setObjectName("formLayout")
        self.tagsLabel = QtWidgets.QLabel(TransactionTagsDialog)
        self.tagsLabel.setObjectName("tagsLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.tagsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tagsLineEdit = QtWidgets.QLineEdit(TransactionTagsDialog)
        self.tagsLineEdit.setObjectName("tagsLineEdit")
        self.horizontalLayout.addWidget(self.tagsLineEdit)
        self.selectTagToolButton = QtWidgets.QToolButton(TransactionTagsDialog)
        self.selectTagToolButton.setObjectName("selectTagToolButton")
        self.horizontalLayout.addWidget(self.selectTagToolButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(TransactionTagsDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)

        self.retranslateUi(TransactionTagsDialog)
        QtCore.QMetaObject.connectSlotsByName(TransactionTagsDialog)

    def retranslateUi(self, TransactionTagsDialog):
        _translate = QtCore.QCoreApplication.translate
        TransactionTagsDialog.setWindowTitle(_translate("TransactionTagsDialog", "Dialog"))
        self.tagsLabel.setText(_translate("TransactionTagsDialog", "Tags"))
        self.tagsLineEdit.setToolTip(_translate("TransactionTagsDialog", "Both existing or new Tag names are valid"))
        self.tagsLineEdit.setPlaceholderText(_translate("TransactionTagsDialog", "Enter Tag names (separated by \';\')"))
        self.selectTagToolButton.setText(_translate("TransactionTagsDialog", "..."))
