# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\welcome_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeDialog(object):
    def setupUi(self, WelcomeDialog):
        WelcomeDialog.setObjectName("WelcomeDialog")
        WelcomeDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        WelcomeDialog.resize(322, 126)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WelcomeDialog.sizePolicy().hasHeightForWidth())
        WelcomeDialog.setSizePolicy(sizePolicy)
        WelcomeDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WelcomeDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.openFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openFilePushButton.setObjectName("openFilePushButton")
        self.gridLayout.addWidget(self.openFilePushButton, 2, 0, 1, 1)
        self.openRecentFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openRecentFilePushButton.setObjectName("openRecentFilePushButton")
        self.gridLayout.addWidget(self.openRecentFilePushButton, 1, 0, 1, 1)
        self.openQuickStartGuidePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openQuickStartGuidePushButton.setObjectName("openQuickStartGuidePushButton")
        self.gridLayout.addWidget(self.openQuickStartGuidePushButton, 1, 1, 1, 1)
        self.createNewFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.createNewFilePushButton.setObjectName("createNewFilePushButton")
        self.gridLayout.addWidget(self.createNewFilePushButton, 0, 0, 1, 1)
        self.quitPushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.quitPushButton.setObjectName("quitPushButton")
        self.gridLayout.addWidget(self.quitPushButton, 2, 1, 1, 1)
        self.openDemoFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openDemoFilePushButton.setObjectName("openDemoFilePushButton")
        self.gridLayout.addWidget(self.openDemoFilePushButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(WelcomeDialog)
        QtCore.QMetaObject.connectSlotsByName(WelcomeDialog)

    def retranslateUi(self, WelcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        WelcomeDialog.setWindowTitle(_translate("WelcomeDialog", "Welcome"))
        self.label.setText(_translate("WelcomeDialog", "WELCOME IMAGE HERE"))
        self.openFilePushButton.setText(_translate("WelcomeDialog", "Open File"))
        self.openRecentFilePushButton.setText(_translate("WelcomeDialog", "Open most recent file"))
        self.openQuickStartGuidePushButton.setText(_translate("WelcomeDialog", "Quick Start Guide"))
        self.createNewFilePushButton.setText(_translate("WelcomeDialog", "New file"))
        self.quitPushButton.setText(_translate("WelcomeDialog", "Quit"))
        self.openDemoFilePushButton.setText(_translate("WelcomeDialog", "Open Demo or Template"))
