# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\dialogs\welcome_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeDialog(object):
    def setupUi(self, WelcomeDialog):
        WelcomeDialog.setObjectName("WelcomeDialog")
        WelcomeDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        WelcomeDialog.resize(250, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WelcomeDialog.sizePolicy().hasHeightForWidth())
        WelcomeDialog.setSizePolicy(sizePolicy)
        WelcomeDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        WelcomeDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WelcomeDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.createNewFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.createNewFilePushButton.setObjectName("createNewFilePushButton")
        self.verticalLayout.addWidget(self.createNewFilePushButton)
        self.openRecentFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openRecentFilePushButton.setObjectName("openRecentFilePushButton")
        self.verticalLayout.addWidget(self.openRecentFilePushButton)
        self.openDemoFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openDemoFilePushButton.setObjectName("openDemoFilePushButton")
        self.verticalLayout.addWidget(self.openDemoFilePushButton)
        self.openFilePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openFilePushButton.setObjectName("openFilePushButton")
        self.verticalLayout.addWidget(self.openFilePushButton)
        self.openQuickStartGuidePushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.openQuickStartGuidePushButton.setObjectName("openQuickStartGuidePushButton")
        self.verticalLayout.addWidget(self.openQuickStartGuidePushButton)
        self.quitPushButton = QtWidgets.QPushButton(WelcomeDialog)
        self.quitPushButton.setObjectName("quitPushButton")
        self.verticalLayout.addWidget(self.quitPushButton)

        self.retranslateUi(WelcomeDialog)
        QtCore.QMetaObject.connectSlotsByName(WelcomeDialog)

    def retranslateUi(self, WelcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        WelcomeDialog.setWindowTitle(_translate("WelcomeDialog", "Welcome"))
        self.label.setText(_translate("WelcomeDialog", "WELCOME IMAGE HERE"))
        self.createNewFilePushButton.setText(_translate("WelcomeDialog", "Create new file"))
        self.openRecentFilePushButton.setText(_translate("WelcomeDialog", "Open most recent file"))
        self.openDemoFilePushButton.setText(_translate("WelcomeDialog", "Open demo file"))
        self.openFilePushButton.setText(_translate("WelcomeDialog", "Open file from browser"))
        self.openQuickStartGuidePushButton.setText(_translate("WelcomeDialog", "Quick Start Guide"))
        self.quitPushButton.setText(_translate("WelcomeDialog", "Quit"))
