# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\reports\attribute_periodic_report.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AttributePeriodicReport(object):
    def setupUi(self, AttributePeriodicReport):
        AttributePeriodicReport.setObjectName("AttributePeriodicReport")
        AttributePeriodicReport.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        AttributePeriodicReport.resize(800, 600)
        AttributePeriodicReport.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(AttributePeriodicReport)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(AttributePeriodicReport)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.actionExpand_All_Income = QtGui.QAction(AttributePeriodicReport)
        self.actionExpand_All_Income.setObjectName("actionExpand_All_Income")
        self.actionExpand_All_Expense = QtGui.QAction(AttributePeriodicReport)
        self.actionExpand_All_Expense.setObjectName("actionExpand_All_Expense")
        self.actionCollapse_All_Income = QtGui.QAction(AttributePeriodicReport)
        self.actionCollapse_All_Income.setObjectName("actionCollapse_All_Income")
        self.actionCollapse_All_Expense = QtGui.QAction(AttributePeriodicReport)
        self.actionCollapse_All_Expense.setObjectName("actionCollapse_All_Expense")

        self.retranslateUi(AttributePeriodicReport)
        QtCore.QMetaObject.connectSlotsByName(AttributePeriodicReport)

    def retranslateUi(self, AttributePeriodicReport):
        _translate = QtCore.QCoreApplication.translate
        AttributePeriodicReport.setWindowTitle(_translate("AttributePeriodicReport", "Category Report"))
        self.actionExpand_All_Income.setText(_translate("AttributePeriodicReport", "Expand All"))
        self.actionExpand_All_Expense.setText(_translate("AttributePeriodicReport", "Expand All"))
        self.actionCollapse_All_Income.setText(_translate("AttributePeriodicReport", "Collapse All"))
        self.actionCollapse_All_Expense.setText(_translate("AttributePeriodicReport", "Collapse All"))
