# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\reports\category_report.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryReport(object):
    def setupUi(self, CategoryReport):
        CategoryReport.setObjectName("CategoryReport")
        CategoryReport.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        CategoryReport.resize(800, 600)
        CategoryReport.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(CategoryReport)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(CategoryReport)
        self.tabWidget.setObjectName("tabWidget")
        self.incomeTab = QtWidgets.QWidget()
        self.incomeTab.setObjectName("incomeTab")
        self.incomeTabHorizontalLayout = QtWidgets.QHBoxLayout(self.incomeTab)
        self.incomeTabHorizontalLayout.setObjectName("incomeTabHorizontalLayout")
        self.incomeTreeView = QtWidgets.QTreeView(self.incomeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incomeTreeView.sizePolicy().hasHeightForWidth())
        self.incomeTreeView.setSizePolicy(sizePolicy)
        self.incomeTreeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.incomeTreeView.setSortingEnabled(True)
        self.incomeTreeView.setObjectName("incomeTreeView")
        self.incomeTreeView.header().setStretchLastSection(False)
        self.incomeTabHorizontalLayout.addWidget(self.incomeTreeView)
        self.tabWidget.addTab(self.incomeTab, "")
        self.expenseTab = QtWidgets.QWidget()
        self.expenseTab.setObjectName("expenseTab")
        self.expenseTabHorizontalLayout = QtWidgets.QHBoxLayout(self.expenseTab)
        self.expenseTabHorizontalLayout.setObjectName("expenseTabHorizontalLayout")
        self.expenseTreeView = QtWidgets.QTreeView(self.expenseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expenseTreeView.sizePolicy().hasHeightForWidth())
        self.expenseTreeView.setSizePolicy(sizePolicy)
        self.expenseTreeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.expenseTreeView.setSortingEnabled(True)
        self.expenseTreeView.setObjectName("expenseTreeView")
        self.expenseTreeView.header().setStretchLastSection(False)
        self.expenseTabHorizontalLayout.addWidget(self.expenseTreeView)
        self.tabWidget.addTab(self.expenseTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(CategoryReport)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CategoryReport)

    def retranslateUi(self, CategoryReport):
        _translate = QtCore.QCoreApplication.translate
        CategoryReport.setWindowTitle(_translate("CategoryReport", "Category Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.incomeTab), _translate("CategoryReport", "Income"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.expenseTab), _translate("CategoryReport", "Expense"))
