# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\reports\tree_and_sunburst_report.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TreeAndSunburstReport(object):
    def setupUi(self, TreeAndSunburstReport):
        TreeAndSunburstReport.setObjectName("TreeAndSunburstReport")
        TreeAndSunburstReport.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TreeAndSunburstReport.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TreeAndSunburstReport)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeViewVerticalLayout = QtWidgets.QVBoxLayout()
        self.treeViewVerticalLayout.setObjectName("treeViewVerticalLayout")
        self.treeViewControlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.treeViewControlsHorizontalLayout.setObjectName("treeViewControlsHorizontalLayout")
        self.expandAllToolButton = QtWidgets.QToolButton(TreeAndSunburstReport)
        self.expandAllToolButton.setObjectName("expandAllToolButton")
        self.treeViewControlsHorizontalLayout.addWidget(self.expandAllToolButton)
        self.collapseAllToolButton = QtWidgets.QToolButton(TreeAndSunburstReport)
        self.collapseAllToolButton.setObjectName("collapseAllToolButton")
        self.treeViewControlsHorizontalLayout.addWidget(self.collapseAllToolButton)
        self.searchLineEdit = QtWidgets.QLineEdit(TreeAndSunburstReport)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.treeViewControlsHorizontalLayout.addWidget(self.searchLineEdit)
        self.treeViewVerticalLayout.addLayout(self.treeViewControlsHorizontalLayout)
        self.treeView = QtWidgets.QTreeView(TreeAndSunburstReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setSortingEnabled(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setStretchLastSection(False)
        self.treeViewVerticalLayout.addWidget(self.treeView)
        self.horizontalLayout.addLayout(self.treeViewVerticalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TreeAndSunburstReport)
        self.label.setText("")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 1)
        self.actionExpand_All = QtGui.QAction(TreeAndSunburstReport)
        self.actionExpand_All.setObjectName("actionExpand_All")
        self.actionCollapse_All = QtGui.QAction(TreeAndSunburstReport)
        self.actionCollapse_All.setObjectName("actionCollapse_All")

        self.retranslateUi(TreeAndSunburstReport)
        QtCore.QMetaObject.connectSlotsByName(TreeAndSunburstReport)

    def retranslateUi(self, TreeAndSunburstReport):
        _translate = QtCore.QCoreApplication.translate
        TreeAndSunburstReport.setWindowTitle(_translate("TreeAndSunburstReport", "Sunburst Report"))
        self.expandAllToolButton.setText(_translate("TreeAndSunburstReport", "..."))
        self.collapseAllToolButton.setText(_translate("TreeAndSunburstReport", "..."))
        self.searchLineEdit.setToolTip(_translate("TreeAndSunburstReport", "<html><head/><body><p>Special characters:</p><p>* matches zero or more of any characters<br/>? matches any single character<br/>[...] matches any character within square brackets</p></body></html>"))
        self.actionExpand_All.setText(_translate("TreeAndSunburstReport", "Expand All"))
        self.actionCollapse_All.setText(_translate("TreeAndSunburstReport", "Collapse All"))
        self.actionCollapse_All.setToolTip(_translate("TreeAndSunburstReport", "Collapse All"))
