# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\reports\table_and_line_chart_report.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TableAndLineChartReport(object):
    def setupUi(self, TableAndLineChartReport):
        TableAndLineChartReport.setObjectName("TableAndLineChartReport")
        TableAndLineChartReport.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TableAndLineChartReport.resize(800, 600)
        TableAndLineChartReport.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(TableAndLineChartReport)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(TableAndLineChartReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TableAndLineChartReport)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 1)
        self.actionExpand_All = QtGui.QAction(TableAndLineChartReport)
        self.actionExpand_All.setObjectName("actionExpand_All")
        self.actionCollapse_All = QtGui.QAction(TableAndLineChartReport)
        self.actionCollapse_All.setObjectName("actionCollapse_All")

        self.retranslateUi(TableAndLineChartReport)
        QtCore.QMetaObject.connectSlotsByName(TableAndLineChartReport)

    def retranslateUi(self, TableAndLineChartReport):
        _translate = QtCore.QCoreApplication.translate
        TableAndLineChartReport.setWindowTitle(_translate("TableAndLineChartReport", "Report"))
        self.actionExpand_All.setText(_translate("TableAndLineChartReport", "Expand All"))
        self.actionCollapse_All.setText(_translate("TableAndLineChartReport", "Collapse All"))
        self.actionCollapse_All.setToolTip(_translate("TableAndLineChartReport", "Collapse All"))
