# Form implementation generated from reading ui file 'd:\Coding\Kapytal\src\views\ui_files\reports\tag_report.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TagReport(object):
    def setupUi(self, TagReport):
        TagReport.setObjectName("TagReport")
        TagReport.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TagReport.resize(800, 600)
        TagReport.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.horizontalLayout = QtWidgets.QHBoxLayout(TagReport)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(TagReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableView)
        self.tabWidget = QtWidgets.QTabWidget(TagReport)
        self.tabWidget.setObjectName("tabWidget")
        self.incomeTab = QtWidgets.QWidget()
        self.incomeTab.setObjectName("incomeTab")
        self.incomeTabVerticalLayout = QtWidgets.QVBoxLayout(self.incomeTab)
        self.incomeTabVerticalLayout.setObjectName("incomeTabVerticalLayout")
        self.tabWidget.addTab(self.incomeTab, "")
        self.expenseTab = QtWidgets.QWidget()
        self.expenseTab.setObjectName("expenseTab")
        self.expenseTabVerticalLayout = QtWidgets.QVBoxLayout(self.expenseTab)
        self.expenseTabVerticalLayout.setObjectName("expenseTabVerticalLayout")
        self.tabWidget.addTab(self.expenseTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(TagReport)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TagReport)

    def retranslateUi(self, TagReport):
        _translate = QtCore.QCoreApplication.translate
        TagReport.setWindowTitle(_translate("TagReport", "Cash Flow Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.incomeTab), _translate("TagReport", "Income"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.expenseTab), _translate("TagReport", "Expense"))
